#!/usr/bin/env python3
"""Alert examples guide"""

print('🚨 ALERT EXAMPLES - WHAT YOU\'LL RECEIVE')
print('=' * 55)
print()
print('After using /add CONTRACT_ADDRESS, you\'ll get these alerts:')
print()
print('📈 MULTIPLIER ALERTS (Gains):')
print('=' * 55)
print()
print('🚀 2X ALERT:')
print('SOL (Solana) is up 2.1x! 🚀')
print('💰 Price: $150.25 → $315.53 (+110.1%)')
print('📊 Market Cap: $70.5B → $148.1B')
print('🕐 Time: 2 hours ago')
print()
print('🚀🚀 5X ALERT:')
print('MEME (MemeToken) hit 5.2x! 🚀🚀')
print('💰 Price: $0.001 → $0.0052 (+420.0%)')
print('📊 Market Cap: $50K → $260K')
print('🕐 Time: 6 hours ago')
print()
print('🌙 100X ALERT:')
print('MOON (MoonShot) reached 100x! 🌙🌙🌙')
print('💰 Price: $0.0001 → $0.01 (+9,900%)')
print('📊 Market Cap: $10K → $1M')
print('🕐 Time: 1 day ago')
print()
print('📉 LOSS ALERTS (Warnings):')
print('=' * 55)
print()
print('⚠️ 50% LOSS WARNING:')
print('RISK (RiskyToken) down -52.3% ⚠️')
print('💰 Price: $1.00 → $0.48')
print('📊 Market Cap: $500K → $238K')
print('🕐 Time: 30 minutes ago')
print()
print('🔴 75% LOSS WARNING:')
print('DROP (DropToken) down -76.8% 🔴')
print('💰 Price: $2.50 → $0.58')
print('📊 Market Cap: $1.2M → $278K')
print('🕐 Time: 1 hour ago')
print()
print('🛡️ RUG DETECTION ALERT:')
print('=' * 55)
print('🚨 POTENTIAL RUG DETECTED!')
print('SCAM (ScamToken) dropped -95.2% in 5 minutes! 💀')
print('💰 Price: $5.00 → $0.24')
print('📊 Market Cap: $2.5M → $120K')
print('⚠️ Consider exiting position immediately!')
print('🕐 Time: Just now')
print()
print('🔄 REAL-TIME UPDATES:')
print('=' * 55)
print('Every 5 seconds, if significant price change (>5%):')
print()
print('📊 SOL UPDATE:')
print('Solana: $150.25 → $157.76 (+5.0%)')
print('Market Cap: $70.5B → $74.0B')
print()
print('🎯 ALL THESE ALERTS GO TO "THE HUNTED" GROUP!')
print('Use /add CONTRACT_ADDRESS to start receiving them!')
