#!/usr/bin/env python3
"""Clean summary of group names"""

print('🏷️  COMPLETE GROUP NAMES SUMMARY')
print('=' * 50)
print()
print('🤖 Bot: @solanaxalertbot')
print('📊 Analysis: Groups where bot has tokens tracked')
print()
print('✅ ACTIVE GROUPS (Bot currently accessible):')
print('=' * 50)
print()
print('1. 📛 GROUP NAME: "Test"')
print('   🆔 Group ID: -4873290500')
print('   👥 Type: Group chat')
print('   🏷️  Username: No public username')
print('   📊 Tokens: 4/4 active tokens')
print('   ✅ Status: Bot has access')
print()
print('2. 📛 PRIVATE CHAT: @Nasirdeen')
print('   🆔 Chat ID: 851782576')
print('   👥 Type: Private chat')
print('   🏷️  Username: @Nasirdeen')
print('   📊 Tokens: 6/6 active tokens')
print('   ✅ Status: Bot has access')
print()
print('❌ INACTIVE GROUPS (Bot lost access):')
print('=' * 50)
print()
print('3. 📛 UNKNOWN GROUP')
print('   🆔 Group ID: -1001234567890')
print('   ❌ Status: Chat not found (deleted/removed)')
print('   📊 Tokens: 1 token (inactive)')
print()
print('4. 📛 UNKNOWN GROUP')
print('   🆔 Group ID: -9999999999')
print('   ❌ Status: Chat not found (deleted/removed)')
print('   📊 Tokens: 0 active tokens')
print()
print('🎯 SUMMARY OF GROUP NAMES:')
print('=' * 50)
print('✅ Currently working in:')
print('   • Group "Test" (4 tokens)')
print('   • Private chat with @Nasirdeen (6 tokens)')
print()
print('❌ Previously worked in:')
print('   • 2 groups that no longer exist')
print()
print('🆕 Ready to add to:')
print('   • Group -1002350881772 (your target group)')
print('   • Any other groups where you add the bot')
print()
print('🎉 Total: Bot is currently active in 2 chats/groups!')
