#!/usr/bin/env python3
"""How to track tokens guide"""

print('🤖 HOW TO TRACK TOKENS IN "THE HUNTED"')
print('=' * 50)
print()
print('❌ WHAT DOES NOT WORK:')
print('   • Just sending a contract address: ABC123...')
print('   • Posting contract addresses in chat')
print('   • Sharing links with contract addresses')
print()
print('✅ WHAT WORKS - USE THESE COMMANDS:')
print('=' * 50)
print()
print('1️⃣ ADD TOKEN COMMAND:')
print('   Format: /add CONTRACT_ADDRESS')
print('   Example: /add So11111111111111111111111111111111111111112')
print('   Example: /add F228BcJAxfjzJhfwMug4VQ4zWYothnuY8qAYStuwpump')
print()
print('2️⃣ WHAT HAPPENS WHEN YOU USE /add:')
print('   ✅ Bot validates the contract address')
print('   ✅ Bot fetches token information (name, symbol, price)')
print('   ✅ Bot starts real-time monitoring (every 5 seconds)')
print('   ✅ Bot sends confirmation message')
print('   ✅ Alerts begin immediately')
print()
print('3️⃣ REMOVE TOKEN COMMAND:')
print('   Format: /remove')
print('   • Shows interactive menu with all tracked tokens')
print('   • Click buttons to select tokens to remove')
print()
print('4️⃣ OTHER USEFUL COMMANDS:')
print('   /status - Check bot status and statistics')
print('   /list - View all tracked tokens in the group')
print()
print('🎯 STEP-BY-STEP TO START TRACKING:')
print('=' * 50)
print('1. Go to "The Hunted" group')
print('2. Type: /add YOUR_CONTRACT_ADDRESS')
print('3. Press Enter')
print('4. Bot confirms and starts monitoring')
print('5. Real-time alerts begin!')
print()
print('💡 EXAMPLE SESSION:')
print('=' * 50)
print('You type: /add So11111111111111111111111111111111111111112')
print()
print('Bot responds:')
print('✅ Successfully added SOL (Solana) to tracking!')
print('💰 Initial Price: $150.25')
print('📊 Market Cap: $70.5B')
print('🔄 Real-time monitoring started!')
print()
print('Then bot sends regular updates and alerts!')
print()
print('🚀 Ready to start? Use /add in "The Hunted" group!')
