#!/usr/bin/env python3
"""Setup guide for The Hunted group"""

print('🎯 "THE HUNTED" GROUP SETUP COMPLETE!')
print('=' * 60)
print()
print('✅ CONFIRMED SETUP:')
print('   🤖 Bot: @solanaxalertbot')
print('   📛 Group: "The Hunted"')
print('   🆔 Group ID: -1002350881772')
print('   👥 Type: Supergroup (41 members)')
print('   🛡️  Bot Status: ADMIN ✅')
print('   🌐 Platform: Railway (24/7 deployment)')
print()
print('🚀 HOW TO USE THE BOT IN "THE HUNTED":')
print('=' * 60)
print()
print('1️⃣ ADD TOKENS TO TRACK:')
print('   Command: /add CONTRACT_ADDRESS')
print('   Example: /add So11111111111111111111111111111111111111112')
print('   • Bot will start monitoring immediately')
print('   • Real-time price updates every 5 seconds')
print()
print('2️⃣ REMOVE TOKENS:')
print('   Command: /remove')
print('   • Bot shows interactive menu to select tokens')
print('   • Click to remove unwanted tokens')
print()
print('3️⃣ CHECK STATUS:')
print('   Command: /status')
print('   • Shows bot operational status')
print('   • Lists monitoring statistics')
print()
print('4️⃣ LIST ALL TOKENS:')
print('   Command: /list')
print('   • Shows all tracked tokens in the group')
print('   • Displays current prices and performance')
print()
print('🎨 ALERTS YOU\'LL RECEIVE IN "THE HUNTED":')
print('=' * 60)
print()
print('📈 MULTIPLIER ALERTS:')
print('   • 2x gains 🚀')
print('   • 5x gains 🚀🚀')
print('   • 10x gains 🚀🚀🚀')
print('   • 20x, 50x, 100x+ gains 🌙')
print()
print('📉 LOSS ALERTS:')
print('   • -50% loss warning ⚠️')
print('   • -75% loss warning 🔴')
print('   • -90% loss warning 💀')
print()
print('🛡️  RUG DETECTION:')
print('   • Real-time rug detection')
print('   • Automatic alerts for suspicious drops')
print('   • Smart filtering to avoid false positives')
print()
print('🔄 CROSS-GROUP FEATURES:')
print('=' * 60)
print('   • If same token is tracked in other groups:')
print('     ✅ Price updates sync across ALL groups')
print('     ✅ Alerts sent to ALL tracking groups')
print('     ✅ Real-time data shared instantly')
print()
print('💡 ENHANCED FEATURES ACTIVE:')
print('=' * 60)
print('   ⚡ 5-second real-time monitoring')
print('   🔄 Cross-group price synchronization')
print('   🚨 Multi-group alert distribution')
print('   💾 Automatic data persistence')
print('   🛡️  Smart rug detection')
print('   📊 Historical price tracking')
print('   🔧 Auto-restart on failures')
print()
print('🎉 "THE HUNTED" IS READY FOR SOLANA ALERTS!')
print('Start by using /add CONTRACT_ADDRESS to track your first token!')
